### PR TITLE
Add given identity-file to JSch identity repository

### LINKED ISSUE #28: Identity file is not picked up outside of "identity repository"
Using the `:identity-file` flag does not work as advertised. It takes the full path, but has to be located in the folder returned by the jsch `getIdentityRepository` to be used.

### PR DESCRIPTION
**Pull request by magnars**
This allows any file to be set as the identity file.

Closes #28

### CODE REVIEW

**Comment by flosell** [comment]
Thanks for fixing, I'm sure this will help people in the future! 

Since I was looking at the code anyway I fixed a small issue I found (looks like `expand-home` returns a file object if it finds something to expand but returns its input otherwise) and changed the end-to-end test to use the new behaviour. 

Two small things: 
* Was there a particular reason why the `JSchException` from `addIdentity` is silently ignored? If we think it might contain something interesting for debugging we should at least log it (similar to what we do in the [ssh-agent support](https://github.com/flosell/lambdacd-git/blob/4b77ddc/src/lambdacd_git/ssh_agent_support.clj#L22))
* Please update the `CHANGELOG.md` (just add a new section for the next release, 0.4.1) and `README.md` so that other users know the `identity-file` setting now works this way

**Comment by magnars** [comment]
Thanks for taking a look!

> Was there a particular reason why the JSchException from addIdentity is silently ignored? 

I did it this way since that's what JGit does. I agree that logging is better. Fixed.

> Please update the CHANGELOG.md and README.md

I have added an entry to the changelog, but didn't see a need to change the readme - the description there already implies this functionality.

**Comment by magnars** [comment]
The reason the README doesn't need an update is because this branch isn't up to date with master. I'll fix that now.

**Comment by magnars** [comment]
This is now rebased on master, including an updated (reverted) README.  Let me know! :-)

**Comment by flosell** [comment]
Looks good to me, thanks for the contribution!

**Pull request merged**
