### PR TITLE
Adding support for git tag and git push

### PR DESCRIPTION
**Pull request by rohte**

### CODE REVIEW

**Comment by flosell** [comment]
This looks really good, thanks for all this work! 

Can you add a small section in `README.md` and `CHANGELOG.md` (along with "(Thanks to @rohte)") so people reading through the changes or the readme are aware this feature now exists and how to use it? 

Other than that, happy to merge.

**Comment by rohte** [comment]
While writing the documentation I discovered, that  I didn't add a function in core. So I added a function which provides a bit of syntactic sugar there.

**Comment by rohte** [comment]
Also, sometimes lein test seems to be stuck (as now in the pipeline). No clue why.

**Comment by flosell** [comment]
Hmm, this looks like a flaky test... I was able to reproduce the same thing behavior locally and on the current master so you most likely did not introduce this flakyness. I'm creating an issue for this (#17). 

Your PR looks good and ready to merge and I'll release your changes as a new version. Thanks for the contribution!

**Pull request merged**
